server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/study
  redis:
    port: 6379
    host: localhost

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    com.ziyi0227: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.ziyi0227.*.entity

